"""add resumen_noticias cache table

Revision ID: ebc41a91fd7e
Revises: 1e466fcc1d03
Create Date: 2026-09-06 21:50:44.854037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc41a91fd7e'
down_revision: Union[str, Sequence[str], None] = '1e466fcc1d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_id'), 'resumenes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumenes_id'), table_name='resumenes')
    op.drop_table('resumenes')
    # ### end Alembic commands ###
